# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d670b2ca04d5bf35912699ef7b3eee5687b4e1f6d8a65ea27ff788cebdcf3fd71fd1005b223df6115d66788cc309d6cae62636aababf84ec74e95e4e30694374

test:
  secret_key_base: 757bc30e7a5ee591f93978c9d331788af537ef90121d59129f9dd2a94bcb0c4f3a62287e2d50ab5df36add21d092347cf9021b75167bb862a8055b9468750b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
